"""Jupyter notebook builder — accumulates pipeline steps as inspectable cells.

Each pipeline phase appends its cells here, producing a single session.ipynb
the human can open, inspect, and re-run top-to-bottom to reproduce all outputs.

Stored at: artifacts/{dataset_id}/session.ipynb

Design goals:
- LLM reasoning appears as markdown cells (clearly marked)
- Pipeline code (clean_pipeline.py, pipeline.py) runs from file references —
  short cells, human opens the file to inspect the implementation
- Intermediate state is inspectable between phases
- Running the notebook end-to-end reproduces the full analysis
"""

import nbformat
from datetime import datetime, timezone
from pathlib import Path

from lib.artifacts import ARTIFACTS_DIR


def _nb_path(dataset_id: str) -> Path:
    return ARTIFACTS_DIR / dataset_id / "session.ipynb"


KERNEL_NAME = "q3d-research"
KERNEL_DISPLAY = "q3d Research (.venv)"


def ensure_kernel_registered() -> bool:
    """Check if the project venv kernel is registered; print instructions if not.

    To register once:
        source .venv/bin/activate
        python -m ipykernel install --user --name q3d-research --display-name "q3d Research (.venv)"
    """
    import subprocess
    result = subprocess.run(
        ["jupyter", "kernelspec", "list", "--json"],
        capture_output=True, text=True,
    )
    if result.returncode == 0:
        try:
            import json as _json
            specs = _json.loads(result.stdout).get("kernelspecs", {})
            return KERNEL_NAME in specs
        except Exception:
            pass
    return False


def load_or_create(dataset_id: str) -> nbformat.NotebookNode:
    """Load existing session notebook, or create a fresh one with setup cells."""
    path = _nb_path(dataset_id)
    if path.exists():
        return nbformat.read(str(path), as_version=4)

    nb = nbformat.v4.new_notebook()
    nb.metadata["kernelspec"] = {
        "display_name": KERNEL_DISPLAY,
        "language": "python",
        "name": KERNEL_NAME,
    }
    nb.metadata["language_info"] = {"name": "python", "version": "3.11"}

    # Title cell
    nb.cells.append(nbformat.v4.new_markdown_cell(
        f"# Pipeline Session: `{dataset_id}`\n\n"
        "Auto-generated by the q3d research pipeline.\n\n"
        "Each section = one pipeline phase.\n"
        "- **Code cells** show exactly what was run — re-runnable top-to-bottom.\n"
        "- **Markdown cells** (marked `[LLM]`) contain LLM reasoning.\n"
        "- Run all cells in order to reproduce the full analysis."
    ))

    # Resolve absolute paths at notebook-write time so they work
    # regardless of where Jupyter is launched from.
    from lib.artifacts import ARTIFACTS_DIR
    from lib.ckan import DATA_DIR
    abs_data   = DATA_DIR / f"{dataset_id}.csv"
    abs_arts   = ARTIFACTS_DIR / dataset_id

    # Setup cell
    nb.cells.append(nbformat.v4.new_code_cell(
        "import importlib.util, sys\n"
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "from pathlib import Path\n\n"
        f"DATASET_ID = '{dataset_id}'\n"
        f"DATA_PATH  = Path(r'{abs_data}')\n"
        f"ARTIFACTS  = Path(r'{abs_arts}')\n\n"
        "df = pd.read_csv(DATA_PATH)\n"
        "print(f'Raw: {{df.shape[0]:,}} rows × {{df.shape[1]}} cols')\n"
        "df.head(3)"
    ))

    return nb


def _phase_banner(action_code: str, action: str, verdict: str | None = None,
                  ts: str | None = None) -> str:
    ts_str = ts or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    verdict_str = f"  |  verdict: **{verdict}**" if verdict else ""
    return f"---\n## Phase {action_code} — {action.upper()}\n*{ts_str}{verdict_str}*"


def add_phase_section(
    nb: nbformat.NotebookNode,
    *,
    action_code: str,
    action: str,
    verdict: str | None = None,
    llm_narrative: str = "",
    code_cells: list[str] | None = None,
    ts: str | None = None,
) -> None:
    """Append a complete phase section to the notebook.

    Args:
        action_code: e.g. "15"
        action: e.g. "clean"
        verdict: pass / fail / marginal
        llm_narrative: the LLM's reasoning for this phase (marked as [LLM])
        code_cells: list of code strings, each becomes one code cell
        ts: ISO timestamp string
    """
    # Phase banner
    nb.cells.append(nbformat.v4.new_markdown_cell(_phase_banner(action_code, action, verdict, ts)))

    # LLM narrative (if any)
    if llm_narrative:
        nb.cells.append(nbformat.v4.new_markdown_cell(
            f"**[LLM]** {action_code}-{action} reasoning:\n\n{llm_narrative}"
        ))

    # Code cells
    for src in (code_cells or []):
        nb.cells.append(nbformat.v4.new_code_cell(src))


def add_pipeline_replay_cell(nb: nbformat.NotebookNode,
                              pipeline_path: str,
                              var_name: str = "df",
                              label: str = "") -> None:
    """Add a code cell that imports and replays a pipeline file.

    Produces:
        spec = importlib.util.spec_from_file_location(...)
        mod  = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        df = mod.run_pipeline(df)
        print(f"After <label>: {df.shape}")
    """
    label_str = label or Path(pipeline_path).stem
    src = (
        f"# Replay: {label_str}\n"
        f"_spec = importlib.util.spec_from_file_location('{label_str}', Path('{pipeline_path}'))\n"
        f"_mod  = importlib.util.module_from_spec(_spec)\n"
        f"_spec.loader.exec_module(_mod)\n"
        f"{var_name} = _mod.run_pipeline({var_name})\n"
        f"print(f'After {label_str}: {{{var_name}.shape[0]:,}} rows × {{{var_name}.shape[1]}} cols')\n"
        f"{var_name}.head(3)"
    )
    nb.cells.append(nbformat.v4.new_code_cell(src))


def add_pipeline_steps_cells(nb: nbformat.NotebookNode, pipeline_path: str,
                               var_name: str = "df") -> None:
    """Expand a pipeline file into one cell per step.

    Each cell contains:
      - The step function definition (copy from file)
      - A call: df = step_name(df)
      - Column diff inspection: prints new columns added

    Deduplicates step names (LLM may redefine the same name across runs).
    Falls back to a single replay cell if the pipeline format is unrecognised.
    """
    import ast
    import re as _re

    src = Path(pipeline_path).read_text()
    lines = src.splitlines()

    # Extract function definitions — last definition for each name wins (matches Python scoping)
    try:
        tree = ast.parse(src)
    except SyntaxError:
        add_pipeline_replay_cell(nb, pipeline_path, var_name=var_name)
        return

    func_sources: dict[str, str] = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            func_src = "\n".join(lines[node.lineno - 1 : node.end_lineno])
            func_sources[node.name] = func_src  # last definition wins

    # Parse STEPS list to get execution order
    steps_match = _re.search(r"STEPS\s*=\s*\[([^\]]+)\]", src, _re.DOTALL)
    if not steps_match:
        add_pipeline_replay_cell(nb, pipeline_path, var_name=var_name)
        return

    raw_names = [s.strip() for s in steps_match.group(1).split(",") if s.strip()]

    # Deduplicate: preserve first-occurrence order (actual execution order sans duplicates)
    seen: set[str] = set()
    step_names: list[str] = []
    for name in raw_names:
        if name not in seen:
            seen.add(name)
            step_names.append(name)

    # Column-tracking setup cell
    nb.cells.append(nbformat.v4.new_code_cell(
        f"_prev_cols = set({var_name}.columns)"
    ))

    for name in step_names:
        func_src = func_sources.get(name)
        if not func_src:
            continue
        cell_src = (
            func_src + "\n\n"
            + f"{var_name} = {name}({var_name})\n"
            + f"_new = [c for c in {var_name}.columns if c not in _prev_cols]\n"
            + f"print(f'After {name}: {{{var_name}.shape[1]}} cols')\n"
            + "if _new: print(f'  + {_new}')\n"
            + f"_prev_cols = set({var_name}.columns)\n"
            + f"{var_name}[_new[:3] if _new else {var_name}.columns[-3:]].head(3)"
        )
        nb.cells.append(nbformat.v4.new_code_cell(cell_src))


def add_cot_cell(nb: nbformat.NotebookNode, step_name: str, reasoning: str) -> None:
    """Append the model's chain-of-thought as a collapsible markdown cell.

    Uses an HTML <details> block so the notebook stays readable at a glance
    while the full reasoning is preserved for audit.

    step_name: label shown in the summary line (e.g. "plan", "step_02", "eval")
    reasoning: prose text before the JSON block — the model's actual thinking
    """
    reasoning = (reasoning or "").strip()
    if not reasoning:
        return
    display = reasoning
    if len(display) > 3000:
        display = display[:2800] + "\n\n*... [truncated — full reasoning in memory/]*"
    source = (
        f"**[COT]** `{step_name}`\n\n"
        f"<details>\n<summary>Model reasoning</summary>\n\n"
        f"{display}\n\n"
        f"</details>"
    )
    nb.cells.append(nbformat.v4.new_markdown_cell(source))


def add_code_cell(nb: nbformat.NotebookNode, source: str) -> None:
    nb.cells.append(nbformat.v4.new_code_cell(source))


def add_markdown_cell(nb: nbformat.NotebookNode, source: str) -> None:
    nb.cells.append(nbformat.v4.new_markdown_cell(source))


def save(nb: nbformat.NotebookNode, dataset_id: str) -> Path:
    path = _nb_path(dataset_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    nbformat.write(nb, str(path))
    return path
