#!/usr/bin/env python3
"""
Phase 15 Cleaner — data quality cleanup before feature engineering.

Separates cleaning (fixing data quality) from engineering (creating features).
Produces a clean_pipeline.py that transforms raw data into rawClean:
  - Parse strings to usable types
  - Handle missing values
  - Flag outliers
  - Drop useless columns
  - Standardize categories

Usage:
    python -m agents.cleaner <dataset_id>
"""

import json
import re as _re
import sys
from datetime import datetime, timezone
from pathlib import Path
from string import Template

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
from lib.db import RunContext
from lib.ckan import fetch_metadata, DATA_DIR
from lib.eda import basic_profile, format_profile
from lib.llm import load_prompt, call_llm_json, DEFAULT_MODEL
from lib.artifacts import (
    write_run_artifact, ensure_human_notes, load_human_notes,
    load_prior_artifacts, ARTIFACTS_DIR, ACTION_CODES, action_dir,
)
from lib.flags import set_flag, check_requirements
from lib import notebook as nb_lib

ACTION = "clean"
ACTION_CODE = ACTION_CODES[ACTION]
PHASE_DIR = action_dir(ACTION_CODE, ACTION)
PROMPT_NAME = f"research-{ACTION_CODE}-{ACTION}"

# Reference to EDA phase for loading column assessment
EDA_CODE = ACTION_CODES["eda"]
EDA_DIR = action_dir(EDA_CODE, "eda")


# ---------------------------------------------------------------------------
# Pipeline helpers (same pattern as deep_analyst, but for cleaning steps)
# ---------------------------------------------------------------------------

PIPELINE_HEADER = '''"""Cumulative cleaning pipeline — re-runnable from raw data.

Auto-generated by agents/cleaner.py. Each step_NN function fixes a data
quality issue. No feature engineering happens here — only cleaning.

Output: rawClean dataframe (same or fewer columns, parsed types, flagged outliers).
"""

import pandas as pd
import numpy as np
import re

'''

PIPELINE_FOOTER_TEMPLATE = """
STEPS = [{step_list}]


def run_pipeline(df: pd.DataFrame) -> pd.DataFrame:
    for step in STEPS:
        df = step(df)
    return df
"""


def get_phase_dir(dataset_id: str) -> Path:
    d = ARTIFACTS_DIR / dataset_id / PHASE_DIR
    d.mkdir(parents=True, exist_ok=True)
    return d


def load_pipeline(dataset_id: str) -> tuple[str, list[str]]:
    """Load existing clean_pipeline.py. Returns (full_code, list_of_step_names)."""
    path = get_phase_dir(dataset_id) / "clean_pipeline.py"
    if not path.exists():
        return "", []
    code = path.read_text()
    names = _re.findall(r"^def (step_\w+)\(", code, _re.MULTILINE)
    return code, names


def _extract_func_pairs(pipeline_code: str) -> list[tuple[str, str]]:
    """Extract (name, code) pairs from pipeline source."""
    if not pipeline_code:
        return []
    body = _re.split(r"\nSTEPS\s*=\s*\[", pipeline_code)[0]
    first_def = body.find("\ndef ")
    if first_def >= 0:
        body = body[first_def + 1:]
    blocks = _re.split(r"(?=^def step_)", body, flags=_re.MULTILINE)
    pairs = []
    for block in blocks:
        block = block.strip()
        if not block:
            continue
        m = _re.match(r"def (step_\w+)\(", block)
        if m:
            pairs.append((m.group(1), block))
    return pairs


def save_pipeline(dataset_id: str, step_funcs: list[tuple[str, str]]):
    """Write clean_pipeline.py from a list of (func_name, func_code) tuples."""
    path = get_phase_dir(dataset_id) / "clean_pipeline.py"
    body = PIPELINE_HEADER
    for _, code in step_funcs:
        body += code.rstrip() + "\n\n\n"
    step_list = ", ".join(name for name, _ in step_funcs)
    body += PIPELINE_FOOTER_TEMPLATE.format(step_list=step_list)
    path.write_text(body)
    return path


# ---------------------------------------------------------------------------
# Step execution
# ---------------------------------------------------------------------------

def execute_step(df: pd.DataFrame, step_code: str) -> tuple[pd.DataFrame, str, str | None]:
    """Execute a single cleaning step. Returns (df_after, result_msg, func_name)."""
    namespace = {"pd": pd, "np": __import__("numpy"), "re": __import__("re")}
    try:
        exec(step_code, namespace)
        step_fn = None
        for k, v in namespace.items():
            if callable(v) and k.startswith("step_"):
                step_fn = v
                break
        if step_fn is None:
            raise RuntimeError("No step_XX function found in generated code")
        df_after = step_fn(df.copy())
        dropped = [c for c in df.columns if c not in df_after.columns]
        added = [c for c in df_after.columns if c not in df.columns]
        parts = []
        if dropped:
            parts.append(f"-{len(dropped)} cols ({', '.join(dropped)})")
        if added:
            parts.append(f"+{len(added)} cols ({', '.join(added)})")
        if not parts:
            parts.append("in-place transform")
        return df_after, f"OK: {'; '.join(parts)}", step_fn.__name__
    except Exception as e:
        return df, f"FAILED: {type(e).__name__}: {e}", None


# ---------------------------------------------------------------------------
# Main run flow
# ---------------------------------------------------------------------------

def run_clean(dataset_id: str) -> dict:
    """Execute one cleaning run: LLM proposes all steps → execute → evaluate."""
    audit_steps = []
    ctx = RunContext(dataset_id, ACTION, ACTION_CODE, "cleaner")
    conn = ctx.conn

    # 1. Prerequisites
    ds = conn.execute("SELECT * FROM datasets WHERE id = ?", (dataset_id,)).fetchone()
    if not ds:
        raise RuntimeError(f"Dataset {dataset_id} not found.")

    # 2. Load current state
    pipeline_code, existing_step_names = load_pipeline(dataset_id)
    func_pairs = _extract_func_pairs(pipeline_code)

    raw_df = pd.read_csv(DATA_DIR / f"{dataset_id}.csv")

    # Replay existing clean pipeline if any
    if func_pairs:
        namespace = {"pd": pd, "np": __import__("numpy"), "re": __import__("re")}
        exec(pipeline_code, namespace)
        df = namespace["run_pipeline"](raw_df.copy())
        print(f"Rebuilt state via clean pipeline: {len(df)} rows, {len(df.columns)} cols ({len(func_pairs)} prior steps)")
    else:
        df = raw_df.copy()
        print(f"Starting from raw data: {len(df)} rows, {len(df.columns)} cols")
    audit_steps.append({"name": "load_state", "detail": f"{len(df)} rows, {len(df.columns)} cols, {len(func_pairs)} prior steps"})

    # 3. Context
    meta = fetch_metadata(dataset_id)
    human_notes = load_human_notes(dataset_id)
    prior_context = load_prior_artifacts(dataset_id, before_action_code=ACTION_CODE)

    profile = basic_profile(df)
    profile_text = format_profile(profile)

    # Load EDA column assessment
    eda_dir = ARTIFACTS_DIR / dataset_id / EDA_DIR
    column_assessment_text = ""
    if eda_dir.exists():
        eda_runs = sorted([d for d in eda_dir.iterdir() if d.is_dir() and d.name.startswith("run-")])
        if eda_runs:
            ca_path = eda_runs[-1] / "tables" / "column_assessment.csv"
            if ca_path.exists():
                column_assessment_text = ca_path.read_text()
                print(f"  Loaded EDA column assessment from {ca_path.parent.parent.name}")
    if not column_assessment_text:
        column_assessment_text = "(no EDA column assessment found)"

    # 4. Ask LLM for cleaning plan
    print("Asking LLM for cleaning plan...")
    prompt_template = load_prompt(PROMPT_NAME)
    prompt = Template(prompt_template).safe_substitute(
        title=meta["name"],
        columns=", ".join(df.columns.tolist()),
        eda_profile=profile_text,
        column_assessment=column_assessment_text,
        human_notes=human_notes or "_(none)_",
    )
    plan = call_llm_json(prompt, max_tokens=3000)

    planned_steps = plan.get("steps", [])
    print(f"  LLM proposed {len(planned_steps)} cleaning steps")
    audit_steps.append({"name": "llm_plan", "detail": f"{len(planned_steps)} steps proposed"})

    # 5. Execute steps
    step_log = []
    step_num_start = len(existing_step_names) + 1

    for i, planned in enumerate(planned_steps):
        step_num = step_num_start + i
        step_name = planned.get("step_name", f"step_{step_num:02d}")
        step_code = planned.get("code", "")
        step_desc = planned.get("description", "")
        print(f"\n  Step {step_num:02d}: {step_name} — {step_desc}")

        df_after, exec_result, func_name = execute_step(df, step_code)
        print(f"    -> {exec_result}")

        if "FAILED" in exec_result:
            audit_steps.append({"name": f"step_{step_num:02d}", "detail": f"FAILED: {step_desc} | {exec_result}"})
            step_log.append({"step_name": step_name, "description": step_desc, "result": exec_result})
            continue

        step_log.append({
            "step_name": func_name or step_name,
            "description": step_desc,
            "action": planned.get("action", "clean"),
            "columns_affected": planned.get("columns_affected", []),
            "result": exec_result,
        })

        func_pairs.append((func_name or step_name, step_code))
        df = df_after
        audit_steps.append({"name": f"step_{step_num:02d}", "detail": f"{func_name}: {step_desc} | {exec_result}"})

    # 6. Save pipeline + state
    save_pipeline(dataset_id, func_pairs)
    after_profile = basic_profile(df)
    after_text = format_profile(after_profile)

    state = {
        "row_count": len(df),
        "original_columns": list(raw_df.columns),
        "current_columns": list(df.columns),
        "steps_applied": len(func_pairs),
        "step_log": step_log,
        "drops": plan.get("drops", []),
        "missing_strategy": plan.get("missing_strategy", {}),
    }
    state_path = get_phase_dir(dataset_id) / "state.json"
    state_path.write_text(json.dumps(state, indent=2))

    print(f"\n  Clean pipeline: {len(func_pairs)} total steps")
    print(f"  State: {len(df)} rows, {len(df.columns)} cols")
    audit_steps.append({"name": "save_state", "detail": f"pipeline: {len(func_pairs)} steps, cols: {len(df.columns)}"})

    # 7. Record in DB
    verdict = plan.get("verdict", "clean")
    combined = {**plan, "step_log": step_log, "after_profile": after_text}
    run_id = ctx.run_id
    ctx.finish(
        verdict=verdict,
        verdict_reason=plan.get("reason", ""),
        llm_response=json.dumps(combined),
        artifact_paths=[
            f"artifacts/{dataset_id}/{PHASE_DIR}/clean_pipeline.py",
            f"artifacts/{dataset_id}/{PHASE_DIR}/{ACTION_CODE}-{ACTION}-{run_id}.md",
        ],
        prompt_template=PROMPT_NAME,
    )
    conn.commit()
    ctx.close()

    # 8. Write artifact
    artifact_path = write_run_artifact(
        run_id=run_id, dataset_id=dataset_id, action=ACTION, action_code=ACTION_CODE,
        agent="cleaner", model=DEFAULT_MODEL,
        title=f"{meta['name']} — data cleaning",
        verdict=verdict,
        steps=audit_steps,
        prompt_text=prompt[:3000],
        llm_response=combined,
        context=f"Cleaning: {len(raw_df.columns)} raw cols → {len(df.columns)} clean cols, "
                f"{len(func_pairs)} steps applied",
        output_dir=get_phase_dir(dataset_id),
    )
    ensure_human_notes(dataset_id, meta["name"])
    print(f"  Artifact: {artifact_path}")

    # Set flags based on what was cleaned
    set_flag(dataset_id, "types_parsed", run_id=run_id,
             detail=f"{len(func_pairs)} cleaning steps")
    set_flag(dataset_id, "missing_handled", run_id=run_id,
             detail=json.dumps(plan.get("missing_strategy", {}))[:200])
    if any("outlier" in s.get("action", "") or "outlier" in s.get("step_name", "")
           for s in planned_steps):
        set_flag(dataset_id, "outliers_flagged", run_id=run_id)

    # Append to session notebook
    try:
        clean_pipeline_path = str(get_phase_dir(dataset_id) / "clean_pipeline.py")
        nb = nb_lib.load_or_create(dataset_id)
        step_names = [s.get("step_name", s.get("name", "?")) for s in planned_steps]
        nb_lib.add_phase_section(
            nb,
            action_code=ACTION_CODE,
            action=ACTION,
            verdict=plan.get("verdict", "clean"),
            llm_narrative=(
                f"**Reason:** {plan.get('reason', '')}  \n"
                f"**Steps:** {', '.join(step_names)}  \n"
                f"**Missing strategy:** {json.dumps(plan.get('missing_strategy', {}))}  \n"
                f"**Drops:** {', '.join(plan.get('drops', []) or [])}"
            ),
            code_cells=[],
        )
        nb_lib.add_pipeline_steps_cells(nb, clean_pipeline_path)
        nb_lib.save(nb, dataset_id)
        print(f"  Notebook updated: session.ipynb")
    except Exception as e:
        import traceback; traceback.print_exc(); print(f"  Notebook write failed: {e}")

    return plan


def main():
    if len(sys.argv) < 2:
        print("Usage: python -m agents.cleaner <dataset_id>")
        sys.exit(1)

    dataset_id = sys.argv[1]
    result = run_clean(dataset_id)
    print(f"\n=== Data Cleaning Complete ===")
    print(f"Verdict: {result.get('verdict', '?')}")
    print(f"Reason:  {result.get('reason', '')}")
    steps = result.get("steps", [])
    print(f"Steps:   {len(steps)} cleaning operations")


if __name__ == "__main__":
    main()
