#!/usr/bin/env python3
"""
Level 2 Deep Analyst — run-based investigation architecture.

Each invocation is a RUN: a multi-step investigation testing one hypothesis.
  1. Reads current state (pipeline.py + state.json)
  2. LLM plans the run: hypothesis + ordered steps
  3. Executes each step, updating pipeline.py + state.json
  4. Generates charts after all steps
  5. LLM evaluates the run holistically
  6. Writes run artifact

Usage:
    python -m agents.deep_analyst <dataset_id> [--max-steps N] [--max-runs N]
"""

import json
import sys
import re as _re
from datetime import datetime, timezone
from pathlib import Path
from string import Template

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import pandas as pd
from lib.db import get_conn, make_run_id
from lib.ckan import fetch_metadata, DATA_DIR
from lib.eda import basic_profile, format_profile, generate_eda_charts
from lib.llm import load_prompt, call_llm_json, DEFAULT_MODEL
from lib.artifacts import (
    write_run_artifact, ensure_human_notes, load_human_notes,
    load_prior_artifacts, ARTIFACTS_DIR, ACTION_CODES, action_dir,
)
from lib.flags import set_flag
from lib import notebook as nb_lib
from lib.llm_parse import join_list

ACTION = "engineer"
ACTION_CODE = ACTION_CODES[ACTION]
PHASE_DIR = action_dir(ACTION_CODE, ACTION)

# References to upstream phases
EDA_CODE = ACTION_CODES["eda"]
EDA_DIR = action_dir(EDA_CODE, "eda")
CLEAN_CODE = ACTION_CODES["clean"]
CLEAN_DIR = action_dir(CLEAN_CODE, "clean")

MAX_STEPS_PER_RUN = 5
MAX_RUNS_PER_INVOKE = 3

# ---------------------------------------------------------------------------
# Pipeline helpers
# ---------------------------------------------------------------------------

PIPELINE_HEADER = '''"""Cumulative transform pipeline — re-runnable from raw data.

Auto-generated by agents/deep_analyst.py. Each step_NN function was proposed
by an LLM and reviewed/editable by a human.
"""

import pandas as pd
import numpy as np
import re
import math

'''

PIPELINE_FOOTER_TEMPLATE = """
STEPS = [{step_list}]


def run_pipeline(df: pd.DataFrame) -> pd.DataFrame:
    for step in STEPS:
        df = step(df)
    return df
"""


def get_phase_dir(dataset_id: str) -> Path:
    d = ARTIFACTS_DIR / dataset_id / PHASE_DIR
    d.mkdir(parents=True, exist_ok=True)
    return d


def load_pipeline(dataset_id: str) -> tuple[str, list[str]]:
    """Load existing pipeline.py. Returns (full_code, list_of_step_names)."""
    path = get_phase_dir(dataset_id) / "pipeline.py"
    if not path.exists():
        return "", []
    code = path.read_text()
    names = _re.findall(r"^def (step_\w+)\(", code, _re.MULTILINE)
    return code, names


def _extract_func_pairs(pipeline_code: str, step_names: list[str]) -> list[tuple[str, str]]:
    """Extract (name, code) pairs from pipeline source, stripping header/footer."""
    if not pipeline_code:
        return []
    # Strip footer (STEPS = [...] onward)
    body = _re.split(r"\nSTEPS\s*=\s*\[", pipeline_code)[0]
    # Strip header (everything before first def)
    first_def = body.find("\ndef ")
    if first_def >= 0:
        body = body[first_def + 1:]
    # Split into function blocks
    blocks = _re.split(r"(?=^def step_)", body, flags=_re.MULTILINE)
    pairs = []
    for block in blocks:
        block = block.strip()
        if not block:
            continue
        m = _re.match(r"def (step_\w+)\(", block)
        if m:
            pairs.append((m.group(1), block))
    return pairs


def save_pipeline(dataset_id: str, step_funcs: list[tuple[str, str]]):
    """Write pipeline.py from a list of (func_name, func_code) tuples."""
    path = get_phase_dir(dataset_id) / "pipeline.py"
    body = PIPELINE_HEADER
    for _, code in step_funcs:
        body += code.rstrip() + "\n\n\n"
    step_list = ", ".join(name for name, _ in step_funcs)
    body += PIPELINE_FOOTER_TEMPLATE.format(step_list=step_list)
    path.write_text(body)
    return path


# ---------------------------------------------------------------------------
# State tracking (lightweight JSON, not full CSV)
# ---------------------------------------------------------------------------

def load_state(dataset_id: str) -> dict | None:
    """Load state.json if it exists."""
    path = get_phase_dir(dataset_id) / "state.json"
    if path.exists():
        return json.loads(path.read_text())
    return None


def save_state(dataset_id: str, df: pd.DataFrame, raw_df: pd.DataFrame,
               step_log: list[dict]) -> Path:
    """Save state.json: schema tracking + sample records."""
    original_cols = list(raw_df.columns)
    current_cols = list(df.columns)
    added = [c for c in current_cols if c not in original_cols]

    # Sample records (first 5 rows, JSON-safe)
    sample = json.loads(df.head(5).to_json(orient="records", date_format="iso"))

    state = {
        "row_count": len(df),
        "original_columns": original_cols,
        "current_columns": current_cols,
        "added_columns": [
            {"name": c, "dtype": str(df[c].dtype)}
            for c in added
        ],
        "steps_applied": len(step_log),
        "step_log": step_log,
        "sample_records": sample,
    }

    path = get_phase_dir(dataset_id) / "state.json"
    path.write_text(json.dumps(state, indent=2))
    return path


def get_chain_summary(conn, dataset_id: str) -> str:
    """Build a summary of prior engineer runs."""
    rows = conn.execute(
        """SELECT id, verdict, verdict_reason, llm_response
           FROM runs WHERE dataset_id = ? AND action = ?
           ORDER BY finished_at""",
        (dataset_id, ACTION),
    ).fetchall()
    if not rows:
        return "(first engineer run — no prior runs)"
    lines = []
    for r in rows:
        try:
            resp = json.loads(r["llm_response"])
            hypothesis = resp.get("hypothesis", "?")
            findings = resp.get("findings", [])
        except (json.JSONDecodeError, TypeError):
            hypothesis, findings = "?", []
        lines.append(f"- run {r['id']}: {r['verdict']} — hypothesis: {hypothesis}")
        lines.append(f"  reason: {r['verdict_reason'][:120]}")
        for f in findings[:2]:
            lines.append(f"    {f[:100]}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Step execution
# ---------------------------------------------------------------------------

def execute_step(df: pd.DataFrame, step_code: str, step_num: int) -> tuple[pd.DataFrame, str, str | None]:
    """Execute a single step function. Returns (df_after, result_msg, func_name)."""
    namespace = {"pd": pd, "np": __import__("numpy"), "re": __import__("re"), "math": __import__("math")}
    try:
        exec(step_code, namespace)
        step_fn = None
        for k, v in namespace.items():
            if callable(v) and k.startswith("step_"):
                step_fn = v
                break
        if step_fn is None:
            raise RuntimeError("No step_XX function found in generated code")
        df_after = step_fn(df.copy())
        new_cols = [c for c in df_after.columns if c not in df.columns]
        result = f"OK: +{len(new_cols)} cols ({', '.join(new_cols)})" if new_cols else "OK: in-place transform"
        return df_after, result, step_fn.__name__
    except Exception as e:
        return df, f"FAILED: {type(e).__name__}: {e}", None


# ---------------------------------------------------------------------------
# Main run flow
# ---------------------------------------------------------------------------

def run_once(dataset_id: str, max_steps: int = MAX_STEPS_PER_RUN) -> dict:
    """Execute one investigation run: plan → steps → charts → evaluate."""
    audit_steps = []
    conn = get_conn()
    run_id = make_run_id()

    # 1. Prerequisites
    ds = conn.execute("SELECT * FROM datasets WHERE id = ?", (dataset_id,)).fetchone()
    if not ds:
        raise RuntimeError(f"Dataset {dataset_id} not found.")

    # 2. Load current state
    pipeline_code, existing_step_names = load_pipeline(dataset_id)
    func_pairs = _extract_func_pairs(pipeline_code, existing_step_names)
    step_num_start = len(existing_step_names) + 1

    raw_df = pd.read_csv(DATA_DIR / f"{dataset_id}.csv")

    # Replay clean pipeline first (if it exists)
    clean_pipeline_path = ARTIFACTS_DIR / dataset_id / CLEAN_DIR / "clean_pipeline.py"
    if clean_pipeline_path.exists():
        import importlib.util
        spec = importlib.util.spec_from_file_location("clean_pipeline", clean_pipeline_path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        base_df = mod.run_pipeline(raw_df.copy())
        print(f"Replayed clean pipeline: {len(base_df)} rows, {len(base_df.columns)} cols")
    else:
        base_df = raw_df.copy()
        print(f"No clean pipeline found — starting from raw data")

    # Reconstruct current df by running engineer pipeline on clean data
    if func_pairs:
        namespace = {"pd": pd, "np": __import__("numpy"), "re": __import__("re"), "math": __import__("math")}
        exec(pipeline_code, namespace)
        df = namespace["run_pipeline"](base_df.copy())
        print(f"Rebuilt state via engineer pipeline: {len(df)} rows, {len(df.columns)} cols ({len(func_pairs)} prior steps)")
    else:
        df = base_df.copy()
        print(f"Starting from {'clean' if clean_pipeline_path.exists() else 'raw'} data: {len(df)} rows, {len(df.columns)} cols")
    audit_steps.append({"name": "load_state", "detail": f"{len(df)} rows, {len(df.columns)} cols, {len(func_pairs)} prior steps"})

    # 3. Context — gather prior findings + human notes + eda tables
    meta = fetch_metadata(dataset_id)
    human_notes = load_human_notes(dataset_id)
    chain_summary = get_chain_summary(conn, dataset_id)
    prior_context = load_prior_artifacts(dataset_id, before_action_code=ACTION_CODE)

    before_profile = basic_profile(df)
    before_text = format_profile(before_profile)

    # Load eda column assessment if it exists
    lv1_dir = ARTIFACTS_DIR / dataset_id / EDA_DIR
    column_assessment_text = ""
    if lv1_dir.exists():
        lv1_runs = sorted([d for d in lv1_dir.iterdir() if d.is_dir() and d.name.startswith("run-")])
        if lv1_runs:
            ca_path = lv1_runs[-1] / "tables" / "column_assessment.csv"
            if ca_path.exists():
                column_assessment_text = ca_path.read_text()
                print(f"  Loaded eda column assessment from {ca_path.parent.parent.name}")
    if not column_assessment_text:
        column_assessment_text = "(no eda column assessment found)"

    # 4. Plan the run
    print("Planning run...")
    plan_template = load_prompt(f"research-{ACTION_CODE}-{ACTION}-plan")
    plan_prompt = Template(plan_template).safe_substitute(
        title=meta["name"],
        columns=", ".join(df.columns.tolist()),
        chain_summary=chain_summary,
        prior_context=prior_context[:3000] if prior_context else "_(no prior level findings)_",
        eda_profile=before_text,
        column_assessment=column_assessment_text,
        human_notes=human_notes or "_(none)_",
    )
    plan = call_llm_json(plan_prompt, max_tokens=2048)
    hypothesis = plan.get("hypothesis", "?")
    planned_steps = plan.get("steps", [])
    print(f"  Hypothesis: {hypothesis}")
    print(f"  Planned steps: {len(planned_steps)}")
    audit_steps.append({"name": "plan_run", "detail": f"hypothesis: {hypothesis}, {len(planned_steps)} steps planned"})

    # 5. Execute steps
    step_log = []  # for state.json
    step_template = load_prompt(f"research-{ACTION_CODE}-{ACTION}-step")
    steps_executed = 0

    for i, planned in enumerate(planned_steps[:max_steps]):
        step_num = step_num_start + i
        print(f"\n  Step {step_num:02d}: {planned.get('step_name', '?')}...")

        # Build step prompt with current state
        current_profile = basic_profile(df)
        step_prompt = Template(step_template).safe_substitute(
            title=meta["name"],
            columns=", ".join(df.columns.tolist()),
            chain_summary=chain_summary,
            eda_profile=format_profile(current_profile),
            human_notes=human_notes or "_(none)_",
        )
        proposal = call_llm_json(step_prompt, max_tokens=2048)
        step_code = proposal.get("code", "")
        step_name = proposal.get("step_name", f"step_{step_num:02d}")
        step_desc = proposal.get("description", "")
        print(f"    -> {step_name}: {step_desc}")

        # Execute
        df_after, exec_result, func_name = execute_step(df, step_code, step_num)
        print(f"    -> {exec_result}")

        if "FAILED" in exec_result:
            audit_steps.append({"name": f"step_{step_num:02d}", "detail": f"FAILED: {step_desc} | {exec_result}"})
            step_log.append({"step_name": step_name, "description": step_desc, "result": exec_result})
            continue  # skip failed step, try next

        # Track new columns
        new_cols = [c for c in df_after.columns if c not in df.columns]
        step_log.append({
            "step_name": func_name or step_name,
            "description": step_desc,
            "action": "append_column" if new_cols else "in_place_transform",
            "columns_added": new_cols,
            "result": exec_result,
        })

        # Update pipeline — replace if same name exists, otherwise append
        new_name = func_name or step_name
        func_pairs = [(n, c) for n, c in func_pairs if n != new_name]
        func_pairs.append((new_name, step_code))
        df = df_after
        steps_executed += 1
        audit_steps.append({"name": f"step_{step_num:02d}", "detail": f"{func_name}: {step_desc} | {exec_result}"})

    # 6. Save pipeline + state
    save_pipeline(dataset_id, func_pairs)
    save_state(dataset_id, df, raw_df, step_log)
    print(f"\n  Pipeline: {len(func_pairs)} total steps")
    print(f"  State: {len(df)} rows, {len(df.columns)} cols")
    audit_steps.append({"name": "save_state", "detail": f"pipeline: {len(func_pairs)} steps, cols: {len(df.columns)}"})

    # 7. Charts (inside the run dir)
    run_dir = get_phase_dir(dataset_id) / f"run-{run_id}"
    run_dir.mkdir(parents=True, exist_ok=True)
    chart_dir = run_dir / "charts"
    chart_subdir = f"charts"  # relative to run dir for artifact links
    print("  Generating charts...")
    after_profile = basic_profile(df)
    after_text = format_profile(after_profile)
    chart_results = generate_eda_charts(df, chart_dir, after_profile)
    chart_desc = "\n".join(f"- {c['description']}" for c in chart_results)

    audit_steps.append({"name": "charts", "detail": f"{len([c for c in chart_results if c['filename']])} charts"})

    # 8. Evaluate run
    print("  Evaluating run...")
    steps_summary = "\n".join(
        f"- {s['step_name']}: {s['description']} → {s['result']}"
        for s in step_log
    )
    eval_template = load_prompt(f"research-{ACTION_CODE}-{ACTION}-eval")
    eval_prompt = Template(eval_template).safe_substitute(
        title=meta["name"],
        hypothesis=hypothesis,
        steps_summary=steps_summary,
        before_cols=before_profile["col_count"],
        before_profile=before_text,
        after_cols=after_profile["col_count"],
        after_profile=after_text,
        chart_descriptions=chart_desc,
        chain_summary=chain_summary,
        human_notes=human_notes or "_(none)_",
    )
    evaluation = call_llm_json(eval_prompt, max_tokens=1024)
    print(f"  Verdict: {evaluation['verdict']}")
    audit_steps.append({"name": "evaluate_run", "detail": f"{evaluation['verdict']}: {evaluation.get('reason', '')[:80]}"})

    # 9. Record in DB
    combined = {**plan, **evaluation, "steps_executed": steps_executed, "step_log": step_log}
    conn.execute(
        """INSERT INTO runs
           (id, dataset_id, action, action_code, agent, status, finished_at,
            prompt_template, llm_response, verdict, verdict_reason, artifact_paths)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            run_id, dataset_id, ACTION, ACTION_CODE, "deep_analyst", "done",
            datetime.now(timezone.utc).isoformat(),
            f"research-{ACTION_CODE}-{ACTION}-plan+step+eval",
            json.dumps(combined),
            evaluation["verdict"],
            evaluation.get("reason", ""),
            json.dumps([
                f"artifacts/{dataset_id}/{PHASE_DIR}/run-{run_id}/artifact.md",
                f"artifacts/{dataset_id}/{PHASE_DIR}/pipeline.py",
            ]),
        ),
    )
    conn.commit()
    conn.close()

    # 10. Write artifact into run dir
    artifact_path = write_run_artifact(
        run_id=run_id, dataset_id=dataset_id, action=ACTION, action_code=ACTION_CODE,
        agent="deep_analyst",
        model=DEFAULT_MODEL, title=f"{meta['name']} — run {run_id}: {hypothesis[:60]}",
        verdict=evaluation["verdict"],
        steps=audit_steps,
        prompt_text=f"[PLAN]\n{plan_prompt[:1500]}\n\n[EVALUATION]\n{eval_prompt[:1500]}",
        llm_response=combined,
        context=f"Hypothesis: {hypothesis}\nPrior runs:\n{chain_summary}",
        charts=chart_results, chart_subdir=chart_subdir,
        output_dir=run_dir,
    )
    ensure_human_notes(dataset_id, meta["name"])
    print(f"  Artifact: {artifact_path}")

    # Set flags
    if steps_executed > 0:
        set_flag(dataset_id, "candidate_features_created", run_id=run_id,
                 detail=f"{steps_executed} steps, {len(df.columns)} cols")
    if evaluation["verdict"] == "sufficient":
        set_flag(dataset_id, "cheap_prune_done", run_id=run_id)

    # Per-run notebook entry: summary only (no replay cells — those go in main() once)
    try:
        nb = nb_lib.load_or_create(dataset_id)
        nb_lib.add_phase_section(
            nb,
            action_code=ACTION_CODE,
            action=ACTION,
            verdict=evaluation.get("verdict", "?"),
            llm_narrative=(
                f"**Run steps:** {steps_executed} | "
                f"**Columns now:** {len(df.columns)}  \n"
                f"**Verdict:** {evaluation.get('verdict', '?')} — {evaluation.get('reason', '')}  \n"
                f"**Findings:** {'; '.join(evaluation.get('findings', []))}"
            ),
            code_cells=[],
        )
        nb_lib.save(nb, dataset_id)
    except Exception as e:
        import traceback; traceback.print_exc(); print(f"  Notebook write failed: {e}")

    return evaluation


def main():
    if len(sys.argv) < 2:
        print("Usage: python -m agents.deep_analyst <dataset_id> [--max-steps N] [--max-runs N]")
        sys.exit(1)

    dataset_id = sys.argv[1]
    max_steps = MAX_STEPS_PER_RUN
    max_runs = MAX_RUNS_PER_INVOKE

    # Simple arg parsing
    args = sys.argv[2:]
    for i, arg in enumerate(args):
        if arg == "--max-steps" and i + 1 < len(args):
            max_steps = int(args[i + 1])
        elif arg == "--max-runs" and i + 1 < len(args):
            max_runs = int(args[i + 1])

    for run_num in range(1, max_runs + 1):
        print(f"\n{'='*50}")
        print(f"RUN {run_num}/{max_runs}")
        print(f"{'='*50}")

        evaluation = run_once(dataset_id, max_steps=max_steps)

        print(f"\n  Verdict: {evaluation['verdict']}")
        print(f"  Reason:  {evaluation.get('reason', '')}")
        if evaluation.get("findings"):
            for f in evaluation["findings"]:
                print(f"    - {f}")

        if evaluation["verdict"] != "continue":
            print(f"\nStopping: verdict is '{evaluation['verdict']}'")
            break
    else:
        print(f"\nRun limit reached ({max_runs}). Stopping for human review.")

    # Append final replay cells to notebook once (after all runs)
    try:
        nb = nb_lib.load_or_create(dataset_id)
        eng_pipeline_path = ARTIFACTS_DIR / dataset_id / PHASE_DIR / "pipeline.py"
        if eng_pipeline_path.exists():
            nb_lib.add_pipeline_steps_cells(nb, str(eng_pipeline_path))
        nb_lib.add_code_cell(nb,
            "# Inspect engineered features\n"
            f"print(f'Columns: {{len(df.columns)}}')\n"
            "df.select_dtypes(include='number').describe().T[['count','mean','std','min','max']]"
        )
        nb_lib.add_code_cell(nb,
            "# Engineered feature distributions\n"
            "import matplotlib.pyplot as plt\n"
            "_num = df.select_dtypes(include='number').columns.tolist()\n"
            "_n = len(_num); _nc = 3; _nr = (_n + _nc - 1) // _nc\n"
            "fig, axes = plt.subplots(_nr, _nc, figsize=(13, _nr * 3))\n"
            "for ax, col in zip(axes.flat, _num):\n"
            "    df[col].dropna().hist(bins=40, ax=ax, color='teal', edgecolor='none', alpha=0.75)\n"
            "    ax.set_title(col, fontsize=8)\n"
            "for ax in axes.flat[_n:]:\n"
            "    ax.set_visible(False)\n"
            "plt.suptitle('Engineered Feature Distributions', fontsize=12)\n"
            "plt.tight_layout(); plt.show()"
        )
        nb_lib.add_code_cell(nb,
            "# Engineered feature correlation heatmap\n"
            "import matplotlib.pyplot as plt, numpy as np\n"
            "_corr = df.select_dtypes(include='number').corr()\n"
            "_sz = max(6, len(_corr))\n"
            "fig, ax = plt.subplots(figsize=(_sz, _sz * 0.85))\n"
            "_im = ax.imshow(_corr.values, cmap='RdBu_r', vmin=-1, vmax=1)\n"
            "ax.set_xticks(range(len(_corr))); ax.set_yticks(range(len(_corr)))\n"
            "ax.set_xticklabels(_corr.columns, rotation=45, ha='right', fontsize=8)\n"
            "ax.set_yticklabels(_corr.columns, fontsize=8)\n"
            "plt.colorbar(_im, ax=ax, shrink=0.8)\n"
            "ax.set_title('Engineered Feature Correlation Matrix')\n"
            "plt.tight_layout(); plt.show()"
        )
        nb_lib.save(nb, dataset_id)
        print(f"  Notebook updated: session.ipynb")
    except Exception as e:
        import traceback; traceback.print_exc(); print(f"  Notebook write failed: {e}")

    # Always show human how to steer the next run
    notes_path = ARTIFACTS_DIR / dataset_id / "human-notes.md"
    print(f"\n--- Next steps ---")
    print(f"  Review tables: artifacts/{dataset_id}/{PHASE_DIR}/run-*/tables/")
    print(f"  Review charts: artifacts/{dataset_id}/{PHASE_DIR}/run-*/charts/")
    print(f"  Steer next run: {notes_path}")
    if evaluation.get("next_hypothesis"):
        print(f"  Agent suggests: {evaluation['next_hypothesis']}")


if __name__ == "__main__":
    main()
